spring:
  application:
    name: Sales-Order-Management-Service
  datasource:
    url: jdbc:mysql://localhost:3306/javabackend
    username: root
    password: Lemlem11!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show:
      sql: true
      
  cloud:
    config:
      enabled: false    
  config:
      import: optional:ConfigServerManagement://localhost:8084
      
resilience4j:
  circuitbreaker:
    instances:
      getAllCustomerDetails:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED
        
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      
      
server:
  port: 8090
